name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish - c Release
      
    # Runs a single command using the runners shell
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@164583b9e44b4fc5910e78feb607ea7c98d3c7b9
      with:
        TOKEN:  ${{ secrets.ACCESS_GITHUB_ADMIN_TOKEN }}
        BRANCH: github-pages # deploy to branch 'gh-pages'
        FOLDER: dist # build location folder
