name: dotnet-build-and-publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish TodoApi.csproj -c Release -o release --nologo
      
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        TOKEN:  ${{ secrets.ACCESS_GITHUB_ADMIN_TOKEN }}
        BRANCH: gh-pages # deploy to branch 'gh-pages'
        FOLDER: release # build location folder
        
        
    # Runs a single command using the runners shell
#    - name: Deploy
#      uses: JamesIves/github-pages-deploy-action@164583b9e44b4fc5910e78feb607ea7c98d3c7b9
#      with:
#        TOKEN:  ${{ secrets.ACCESS_GITHUB_ADMIN_TOKEN }}
#        BRANCH: github-pages # deploy to branch 'gh-pages'
#        FOLDER: release/wwwroot # build location folder
